### ISSUE TITLE
Add CR parameter for turning on debug loggin for benchmark-wrapper

### ISSUE THREAD

**Issue by acalhounRH** [cloud-bulldozer/benchmark-operator#389]
Currently we do not support the ability to enable debug logging for benchmark-wrapper via the CR file. Adding this ability will give users and developers the ability to enable/disable debug logging without having to rerun workload manually.

**Comment by jtaleric** [comment]
@acalhounRH what is your thoughts on this?

**Comment by bengland2** [comment]
Are you talking about logging the output from the pods?   I'd like to see pod output logged to a file even if the test is successful, just so that we can verify that the pod is doing what we think it is supposed to do.  Also, benchmark-operator logs are insanely hard to read, I had to write a [parse-kube-pod-log.py](http://perf1.perf.lab.eng.bos.redhat.com/pub/bengland/public/openshift/ripsaw/parse-kube-pod-log.py)  script to even look at it.
