### ISSUE TITLE
Merge elasticsearch.server and prometheus.server

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/benchmark-operator#419]
Merge elasticsearch.server and prometheus.server variables. These variables are redundant and led to confusion as I don't see a clear reason to send metadata metrics and prometheus metrics to different ES instances.

**Comment by dry923** [comment]
@rsevilla87 this was setup in a way to allow us to send to different es servers as there were large concerns over the performance impact of sending the prom data to a single (potentially undersized) es server. Additionally in the wrapper it is configured to take a separate values.

@acalhounRH can you provide some comments here as well?

**Comment by rsevilla87** [comment]
Yeah, I know. However, in what cases are we sending metrics are we sending documents to different ES instances?
This is an effort to simplify things that can led to confusion.

**Comment by dry923** [comment]
We are not yet. It was added into the wrapper but not used yet.

**Comment by acalhounRH** [comment]
@dry923 Is correct, we set this up on Arakash￼'s request, due to fears we would over load the test result ES server. 

The ideal is that test result(s) indexing by the entire team should not be interrupted￼ due to the load of prom data being indexed. If overtime we determine there is no significant amount of stress incurred by prom data indexing we will revert to using a single ES server. 

Prom indexing is significant and we should use caution￼ before moving forward.

**Comment by dry923** [comment]
@rsevilla87 I believe this is resolved w/ the name change via https://github.com/cloud-bulldozer/benchmark-operator/pull/436 correct?

**Comment by rsevilla87** [comment]
> @rsevilla87 I believe this is resolved w/ the name change via #436 correct?

yes!
