### ISSUE TITLE
Loop Nesting in Distributed FIO test

### ISSUE THREAD

**Issue by shekharberry** [cloud-bulldozer/benchmark-operator#579]
Currently in Distributed FIO testing the looping is:
-for each value of numjobs (fio processes per pod)
--for each block size
----for each workload type (i.e. job file)
------ for each sample
-------- run fio

Whereas we want the samples for each test type to be spaced as far apart in time as possible to be able to show that the system's performance remains stable over the duration of the entire workload and in this regard the proposed looping should be:

-for each sample
--for each value of numjobs (fio processes per pod)
----for each block size
------for each workload type (i.e. /read/write/randread/randwrite/randrw)
--------run fio

Please let me know your thoughts on this.

**Comment by acalhounRH** [comment]
The problem with this is how benchmark-operator and wrapper perform this loop. currently operator breaks down the list or variables into specific permutations and the wrapper will run them for X sample times.  if the above aproach is needed you would have to send benchmark-wrapper the inclusive test config containing all possible test options, rather than the exact job file. you would then need to develop a method for breaking down the yaml test config into specific job files. This would need a significant level of effort to be done.
