### ISSUE TITLE
Public Archive of benchmark-operator

### ISSUE THREAD

**Issue by jtaleric** [cloud-bulldozer/benchmark-operator#822]
benchmark-operator is no longer being maintained or used within Red Hat. 

I am proposing we move the repo to a public archive.

**Comment by a-thorat** [comment]
@jtaleric @krishvoor we are planning to use this operator for our RH OCP v4.14 cluster performance test. But since you mentioned no longer maintained i am afraid we should look for another tool/operator.
Could you please guide me for another operator/tool i can use for performance test? I came across kubestone. 
Mainly planning to test for 
[Network performance]
[Disk performance]
[HTTP performance]
[Kubernetes resources performance]

**Comment by krishvoor** [comment]
Hi @a-thorat, we have 
>[Network performance]

[k8s-netperf](https://github.com/cloud-bulldozer/k8s-netperf) will help you with East-West Network Testing

>[Kubernetes resources performance]

[kube-burner](https://kube-burner.github.io/kube-burner/latest/) is a performance and scale test orchestration toolset.
Kube-burner will help you perform some of these:
```
Create, delete, read, and patch Kubernetes resources at scale.
Prometheus metric collection and indexing.
Measurements.
Alerting.
```

> [HTTP Performance]

If you are looking for a workload with benchmark termination as HTTP, edge, reencrypt & passthrough you can take a look at [ingress-perf](https://github.com/cloud-bulldozer/ingress-perf)

**Comment by a-thorat** [comment]
@krishvoor 
Thank you for your response.
Surely, will explore provided directions and check how good fit with our env. 
Thank you and Appreciate your help.
